from sqlalchemy import Column, Integer, String, Text, Enum, ForeignKey, Index, text, DateTime, Date, Time, Boolean, BIGINT, UniqueConstraint
from typing import List

# TINYINT 대신 Integer 사용하기 바랍니다.
# from sqlalchemy.dialects.mysql import TINYINT
from sqlalchemy.orm import DynamicMapped, Mapped, relationship, declarative_base
from datetime import datetime, date
from src.database import DBConnect, MySQLCharsetMixin

Base = declarative_base(cls=MySQLCharsetMixin)

DB_TABLE_PREFIX = DBConnect().table_prefix or "g6_"


class Config(Base):
    """
    환경설정 테이블
    """

    __tablename__ = DB_TABLE_PREFIX + "config"

    cf_id = Column(Integer, primary_key=True)
    cf_title = Column(String(255), nullable=False, default="")
    cf_theme = Column(String(100), nullable=False, default="")
    cf_admin = Column(String(100), nullable=False, default="")
    cf_admin_email = Column(String(100), nullable=False, default="")
    cf_admin_email_name = Column(String(100), nullable=False, default="")
    cf_add_script = Column(Text, nullable=False, default="")
    cf_use_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_point_term = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_copy_log = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_email_certify = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_login_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_cut_name = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_nick_modify = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_new_skin = Column(String(50), nullable=False, default="")
    cf_new_rows = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_search_skin = Column(String(50), nullable=False, default="")
    cf_connect_skin = Column(String(50), nullable=False, default="")
    cf_faq_skin = Column(String(50), nullable=False, default="")
    cf_read_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_write_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_comment_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_download_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_write_pages = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_mobile_pages = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_link_target = Column(String(50), nullable=False, default="")
    cf_bbs_rewrite = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_delay_sec = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_filter = Column(Text, nullable=False, default="")
    cf_possible_ip = Column(Text, nullable=False, default="")
    cf_intercept_ip = Column(Text, nullable=False, default="")
    cf_analytics = Column(Text, nullable=False, default="")
    cf_add_meta = Column(Text, nullable=False, default="")
    cf_member_skin = Column(String(50), nullable=False, default="")
    cf_use_homepage = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_req_homepage = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_tel = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_req_tel = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_hp = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_req_hp = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_addr = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_req_addr = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_signature = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_req_signature = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_profile = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_req_profile = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_register_level = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_register_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_icon_level = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_use_recommend = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_recommend_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_leave_day = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_search_part = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_use = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_wr_super_admin = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_wr_group_admin = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_wr_board_admin = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_wr_write = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_wr_comment_all = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_mb_super_admin = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_mb_member = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_email_po_super_admin = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_prohibit_id = Column(Text, nullable=False, default="")
    cf_prohibit_email = Column(Text, nullable=False, default="")
    cf_new_del = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_memo_del = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_visit_del = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_popular_del = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_optimize_date = Column(String(10), nullable=False, default="")
    cf_use_member_icon = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_member_icon_size = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_member_icon_width = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_member_icon_height = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_member_img_size = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_member_img_width = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_member_img_height = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_login_minutes = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_image_extension = Column(String(255), nullable=False, default="")
    cf_flash_extension = Column(String(255), nullable=False, default="")
    cf_movie_extension = Column(String(255), nullable=False, default="")
    cf_formmail_is_member = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_page_rows = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_mobile_page_rows = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_visit = Column(String(255), nullable=False, default="")
    cf_max_po_id = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_stipulation = Column(Text, nullable=False, default="")
    cf_privacy = Column(Text, nullable=False, default="")
    cf_open_modify = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_memo_send_point = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_mobile_new_skin = Column(String(50), nullable=False, default="")
    cf_mobile_search_skin = Column(String(50), nullable=False, default="")
    cf_mobile_connect_skin = Column(String(50), nullable=False, default="")
    cf_mobile_faq_skin = Column(String(50), nullable=False, default="")
    cf_mobile_member_skin = Column(String(50), nullable=False, default="")
    cf_captcha_mp3 = Column(String(255), nullable=False, default="")
    cf_editor = Column(String(50), nullable=False, default="")
    cf_cert_use = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_cert_find = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_cert_ipin = Column(String(255), nullable=False, default="")
    cf_cert_hp = Column(String(255), nullable=False, default="")
    cf_cert_simple = Column(String(255), nullable=False, default="")
    cf_cert_kg_cd = Column(String(255), nullable=False, default="")
    cf_cert_kg_mid = Column(String(255), nullable=False, default="")
    cf_cert_kcb_cd = Column(String(255), nullable=False, default="")
    cf_cert_kcp_cd = Column(String(255), nullable=False, default="")
    cf_lg_mid = Column(String(100), nullable=False, default="")
    cf_lg_mert_key = Column(String(100), nullable=False, default="")
    cf_cert_limit = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_cert_req = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_sms_use = Column(String(255), nullable=False, default="")
    cf_sms_type = Column(String(10), nullable=False, default="")
    cf_icode_id = Column(String(255), nullable=False, default="")
    cf_icode_pw = Column(String(255), nullable=False, default="")
    cf_icode_server_ip = Column(String(50), nullable=False, default="")
    cf_icode_server_port = Column(String(50), nullable=False, default="")
    cf_icode_token_key = Column(String(100), nullable=False, default="")
    cf_googl_shorturl_apikey = Column(String(50), nullable=False, default="")
    cf_social_login_use = Column(Integer, nullable=False, default=0, server_default=text("0"))
    cf_social_servicelist = Column(String(255), nullable=False, default="")
    cf_payco_clientid = Column(String(100), nullable=False, default="")
    cf_payco_secret = Column(String(100), nullable=False, default="")
    cf_facebook_appid = Column(String(100), nullable=False, default="")
    cf_facebook_secret = Column(String(100), nullable=False, default="")
    cf_twitter_key = Column(String(100), nullable=False, default="")
    cf_twitter_secret = Column(String(100), nullable=False, default="")
    cf_google_clientid = Column(String(100), nullable=False, default="")
    cf_google_secret = Column(String(100), nullable=False, default="")
    cf_naver_clientid = Column(String(100), nullable=False, default="")
    cf_naver_secret = Column(String(100), nullable=False, default="")
    cf_kakao_rest_key = Column(String(100), nullable=False, default="")
    cf_kakao_client_secret = Column(String(100), nullable=False, default="")
    cf_kakao_js_apikey = Column(String(100), nullable=False, default="")
    cf_captcha = Column(String(100), nullable=False, default="")
    cf_recaptcha_site_key = Column(String(100), nullable=False, default="")
    cf_recaptcha_secret_key = Column(String(100), nullable=False, default="")
    cf_1_subj = Column(String(255), nullable=False, default="")
    cf_2_subj = Column(String(255), nullable=False, default="")
    cf_3_subj = Column(String(255), nullable=False, default="")
    cf_4_subj = Column(String(255), nullable=False, default="")
    cf_5_subj = Column(String(255), nullable=False, default="")
    cf_6_subj = Column(String(255), nullable=False, default="")
    cf_7_subj = Column(String(255), nullable=False, default="")
    cf_8_subj = Column(String(255), nullable=False, default="")
    cf_9_subj = Column(String(255), nullable=False, default="")
    cf_10_subj = Column(String(255), nullable=False, default="")
    cf_1 = Column(String(255), nullable=False, default="")
    cf_2 = Column(String(255), nullable=False, default="")
    cf_3 = Column(String(255), nullable=False, default="")
    cf_4 = Column(String(255), nullable=False, default="")
    cf_5 = Column(String(255), nullable=False, default="")
    cf_6 = Column(String(255), nullable=False, default="")
    cf_7 = Column(String(255), nullable=False, default="")
    cf_8 = Column(String(255), nullable=False, default="")
    cf_9 = Column(String(255), nullable=False, default="")
    cf_10 = Column(String(255), nullable=False, default="")
